baseURL = 'https://willweiao.github.io/'
languageCode = 'en-us'
title = 'willweiao.blog'
theme = "PaperMod"

[params]
  ShowCodeCopyButtons = true
  homeInfoParams = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowToc = true
  math = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'